/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package api.iterator.backend;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import javax.annotation.PostConstruct;
import java.util.TimeZone;

@SpringBootApplication
public class App {
    @Value(value = "${app.timezone}")
    String appTimeZone;

    @PostConstruct
    void init() {
        TimeZone.setDefault(TimeZone.getTimeZone(appTimeZone));
    }

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
